title: Aman Kumar # your name (or website title) here
logo: "/images/Aman_Kumar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  Data Scientist with 2+ years of experience in Analytics, Natural Language Processing, Machine Learning and Computer Vision.
  </p>
  
  <br>
  Master's in Data Science Graduate from University of Pennsylvania (IVY League) 
  <br><br>
  <a href="https://www.linkedin.com/in/amankumar36/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
