title: Aman Kumar # your name (or website title) here
logo: "/images/Aman_Kumar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <ul>
  <li> Data Scientist with 2+ years of experience in Analytics, Natural Language Processing, Machine Learning, and Computer Vision.
  <li> Research Assistant (RA) at University of Pennsylvania (UPenn) Computer and Information Science Department.
  <li> RA at Wharton School of the University of Pennsylvania Management Department.
  <li> Head Teaching Assistant (TA) for course CIS 5450 Big Data Analytics.  
 </ul>
  <br>
  Master's in Data Science Graduate from University of Pennsylvania.
  <br><br>
  <a href="https://www.linkedin.com/in/amankumar36/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
